trainer:
  accelerator: "gpu"
  devices: 1
  # precision: 16
  min_epochs: 5
  max_epochs: 5
  benchmark: True
  log_every_n_steps: 4
  # overfit_batches: 1
experiment:
  task: "dfc2022"
  module:
    loss: "focal"
    model: "unet"
    backbone: "resnet18"
    weights: True
    lr: 1e-3
    patience: 6
    in_channels: 4
    num_classes: 16
    ignore_index: 0  # classes 0 & 15 are not used in scoring
datamodule:
    root_dir: "data/"
    batch_size: 128
    num_workers: 6
    val_split_pct: 0.1
    patch_size: null
    predict_on: "val"
    img_size: 512
    n_tiles: 4